### ISSUE TITLE
use response selector for chitchat/faq

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa-demo#344]
makes the most sense instead of #289

**Comment by akelad** [comment]
can you close that issue then?

**Comment by rgstephens** [comment]
Implementation notes:

- `closetheloop.md` has stories off of intent `ask_faq_differencecorenlu` that invoke both `utter_ask_faq_differencecorenlu` (via the `actions_faq`) & `utter_ask_explain_nlucorex`. In the `faqs.md` stories only invoke `utter_ask_faq_differencecorenlu`
  - `utter_ask_explain_nlucorex` is used many other stories, don't remove

Issues:

- `ask_faq_rasax` listed in intents but no intent definition
- Five of the FAQ's have associated `explain` intents and utterances
  - `ask_faq_ee`, `ask_faq_languages`, `ask_faq_voice`, `ask_faq_slots`

```
* ask_faq_ee
    - action_faqs
* explain
    - utter_faq_ee_more
```

Non-Retrieval Action FAQs/Chitchat intents:

- `

ToDo:

- [ ] Remove stories
- [ ] Clean-up `ActionFaqs`, only used for the multi-turn FAQs
- [ ] `ActionChitchat` from `actions.py`
- [ ] `domain.yml` remove individual `ask_` & `ask_faq` intents & actions
- [ ] run `rasa data validate`

**Comment by rgstephens** [comment]
I think the following issues prevent us from using ResponseSelectors with the rasa-demo but we should confirm and discuss:

- We can't use the TwoStageFallbackPolicy with ResponseSelector. The problem is that the intent `ask_faq/python_version` is grouped into the single retriever intent and placed in the tracker store as `ask_faq`. As a result, the `ActionDefaultAskAffirmation` class cannot determine possible intents to respond with.
- Multiple responses not [supported](https://forum.rasa.com/t/supervised-response-selector-experimental/13714/24), first response is always returned
- Plain text responses [only](https://forum.rasa.com/t/supervised-response-selector-experimental/13714/25)
- Multiline responses not supported

**Comment by erohmensing** [comment]
> ask_faq_rasax listed in intents but no intent definition

please add one! might have lost it when that got changed from ask_faq_platform

> ask_faq_differencerasarasax & ask_faq_rasax intent exists but no stories

think this is still relevant in the actions server, check for `action_faq` -- this is the big action response selector is to replace

> Unused response templates...

OOS for this PR, don't worry about it

**Comment by ArjaanBuijk** [comment]
@rgstephens , is this causing the issue https://github.com/RasaHQ/rasa-demo/issues/351 ?
(ActionDefaultAskAffirmation not working properly)

**Comment by rgstephens** [comment]
@ArjaanBuijk No, the ResponseSelector has not been deployed so it is not associated with #351

**Comment by erohmensing** [comment]
Now only blocked by upgrading sara to 1.9 🚀

**Comment by akelad** [comment]
lmao, @melindaloubser1 may as well change that PR to upgrade to 1.9 :P can you just post the results of crossval for the new config on the PR manually so we can take a look? We'll address fixing the results posting later

**Comment by melindaloubser1** [comment]
Sure, I'll do that
